In [131]:
path = "data_science_python/Chicago_Public_Schools_-_School_Admissions_Information_SY2122.csv"
#import json
#records = [json.loads(line) for line in open(path)]
import pandas as pan
df_admit = pan.read_csv(path, sep=",") # read file into dataframe 
df_admit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School_ID                 861 non-null    int64
 1   Short_Name                861 non-null    object
 2   Long_Name                 861 non-null    object
 3   Primary_Category          861 non-null    object
 4   Program_Type              861 non-null    object
 5   Program_Group             861 non-null    object
 6   Address                   861 non-null    object
 7   City                      861 non-null    object
 8   State                     861 non-null    object
 9   Zip                       861 non-null    int64
 10  Phone                     861 non-null    object
 11  Fax                       860 non-null    object
 12  CPS_School_Profile        861 non-null    object
 13  Website                   861 non-null    object
 14  Program_Grades_Served     861 non-null    object
 15  Application_Requirements  861 non-null    object
 16  Program_Selections        861 non-null    object
 17  How_To_Apply              861 non-null    object
 18  Deadline                  0 non-null      float64
 19  School_Latitude           861 non-null    float64
 20  School_Longitude          861 non-null    float64
 21  Location                  861 non-null    object
dtypes: float64(3), int64(2), object(17)
memory usage: 148.1+ KB

In [10]:
df_admit['Deadline'] = 0 # set the value of Deadline to 0 instead of NaN which may cause error
df_admit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School_ID                 861 non-null    int64
 1   Short_Name                861 non-null    object
 2   Long_Name                 861 non-null    object
 3   Primary_Category          861 non-null    object
 4   Program_Type              861 non-null    object
 5   Program_Group             861 non-null    object
 6   Address                   861 non-null    object
 7   City                      861 non-null    object
 8   State                     861 non-null    object
 9   Zip                       861 non-null    int64
 10  Phone                     861 non-null    object
 11  Fax                       860 non-null    object
 12  CPS_School_Profile        861 non-null    object
 13  Website                   861 non-null    object
 14  Program_Grades_Served     861 non-null    object
 15  Application_Requirements  861 non-null    object
 16  Program_Selections        861 non-null    object
 17  How_To_Apply              861 non-null    object
 18  Deadline                  861 non-null    int64
 19  School_Latitude           861 non-null    float64
 20  School_Longitude          861 non-null    float64
 21  Location                  861 non-null    object
dtypes: float64(2), int64(3), object(17)
memory usage: 148.1+ KB

In [132]:
df_admit[df_admit.duplicated(keep = False)] # check for duplicate record :keep ={first, last, false}
df_admit = df_admit.drop_duplicates() # on record removed row 285
# check for schools programs
df_a_prog = df_admit['Program_Group'] # unique list of program admitted for
df_a_prog.value_counts()
#

General Education                                          347
Fine & Performing Arts                                      89
World Language                                              68
International Baccalaureate (IB)                            54
STEM                                                        42
Selective Enrollment                                        34
Significantly Modified Curriculum w/ Moderate Supports      31
Technology                                                  20
Media & Communication Arts                                  19
Scholastic Academy                                          15
Health Sciences                                             15
Dual Language                                               12
Culinary & Hospitality                                      12
Manufacturing & Engineering                                 11
Significantly Modified Curriculum w/ Intensive Supports     10
Military & Service Leadership                                9
Information Technology                                       8
Honors                                                       7
Law & Public Safety                                          6
Construction & Architecture                                  6
Transportation                                               5
Academic Center                                              5
Business & Finance                                           5
Deaf/Hard of Hearing                                         4
Education & Training                                         4
MultiSensory                                                 4
Montessori                                                   4
Agriculture & Horticulture                                   3
Humanities                                                   2
Career Academy                                               2
Personal Care Services                                       2
Journalism & Writing                                         2
Visual Impairment                                            2
Regional Gifted                                              1
Name: Program_Group, dtype: int64

In [132]:
df_admit[df_admit.duplicated(keep = False)] # check for duplicate record :keep ={first, last, false}
df_admit = df_admit.drop_duplicates() # on record removed row 285
# check for schools programs
df_a_prog = df_admit['Program_Group'] # unique list of program admitted for
df_a_prog.value_counts()
#

General Education                                          347
Fine & Performing Arts                                      89
World Language                                              68
International Baccalaureate (IB)                            54
STEM                                                        42
Selective Enrollment                                        34
Significantly Modified Curriculum w/ Moderate Supports      31
Technology                                                  20
Media & Communication Arts                                  19
Scholastic Academy                                          15
Health Sciences                                             15
Dual Language                                               12
Culinary & Hospitality                                      12
Manufacturing & Engineering                                 11
Significantly Modified Curriculum w/ Intensive Supports     10
Military & Service Leadership                                9
Information Technology                                       8
Honors                                                       7
Law & Public Safety                                          6
Construction & Architecture                                  6
Transportation                                               5
Academic Center                                              5
Business & Finance                                           5
Deaf/Hard of Hearing                                         4
Education & Training                                         4
MultiSensory                                                 4
Montessori                                                   4
Agriculture & Horticulture                                   3
Humanities                                                   2
Career Academy                                               2
Personal Care Services                                       2
Journalism & Writing                                         2
Visual Impairment                                            2
Regional Gifted                                              1
Name: Program_Group, dtype: int64

In [53]:
#df_admit = df_admit.drop(['How_To_Apply','Application_Requirements','Deadline'], axis=1) # remove unwanted columns
#df_admit.info()
df_admit['Primary_Category'].value_counts() # Primary catergories of programs

ES    515
HS    338
MS      7
Name: Primary_Category, dtype: int64

In [221]:
#df_admit['Program_Type'] # program type in chicago schools
import numpy as np
# write the below for loop as pan.Series function
#pan.Series(x.replace(df_admit.Short_Name, '') for x in df_admit.Program_Type)

for ind in df_admit.index:
    r = df_admit['Short_Name'][ind]
    s = df_admit['Program_Type'][ind]
    t = s.replace(r, '').strip(' - ')
    df_admit.loc[:,('Program_Code')][ind] = t.lower() # avoid SettingWithCopyWarning by using .loc method of the dataframe
    
df_admit

C:\Users\efaki\AppData\Local\Temp\ipykernel_21216\20677175.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_admit.loc[:,('Program_Code')][ind] = t.lower() # avoid SettingWithCopyWarning by using .loc method of the dataframe

,School_ID,Short_Name,Long_Name,Primary_Category,Program_Type,Program_Group,Address,City,State,Zip,...,Website,Program_Grades_Served,Application_Requirements,Program_Selections,How_To_Apply,Deadline,School_Latitude,School_Longitude,Location,Program_Code
0,609756,CURIE HS,Marie Sklodowska Curie Metropolitan High School,HS,CURIE HS - International Baccalaureate (IB),International Baccalaureate (IB),4959 S ARCHER AVE,Chicago,Illinois,60632,...,https://www.curiehs.org,9,None,Selection Type: Point GPA: 2.5 HS Admissio...,None,NaN,41.803060,-87.722042,POINT (-87.722042 41.80306),international baccalaureate (ib)
1,609867,COOPER,Peter Cooper Elementary Dual Language Academy,ES,COOPER - Open Enrollment,World Language,1624 W 19TH ST,Chicago,Illinois,60608,...,https://cps.edu/cooper,K-8,none,Selection Type: Lottery GPA: none Priority...,none,NaN,41.856031,-87.667227,POINT (-87.667227 41.856031),open enrollment
2,610239,DALEY,Richard J Daley Elementary Academy,ES,DALEY - Open Enrollment,General Education,5024 S WOLCOTT AVE,Chicago,Illinois,60609,...,https://rjdaley.org,K-8,none,Selection Type: Lottery GPA: none Priority...,none,NaN,41.802343,-87.672206,POINT (-87.672206 41.802343),open enrollment
3,609679,PROSSER HS,Charles Allen Prosser Career Academy High School,HS,PROSSER HS - Significantly Mod Curr/Moderate,Significantly Modified Curriculum w/ Moderate ...,2148 N LONG AVE,Chicago,Illinois,60639,...,https://prosseracademy.org,9,Cluster and Review,Selection Type: Lottery GPA: None HS Admis...,Cluster and Review,NaN,41.920059,-87.761048,POINT (-87.761048 41.920059),significantly mod curr/moderate
4,610381,BRONZEVILLE HS,Bronzeville Scholastic Academy High School,HS,BRONZEVILLE HS - General Education,General Education,4934 S WABASH AVE,Chicago,Illinois,60615,...,https://bronzevillescholastic.org,9,None,Selection Type: Lottery GPA: None HS Admis...,None,NaN,41.805204,-87.625004,POINT (-87.625004 41.805204),general education
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,610323,BOWEN HS,Bowen High School,HS,BOWEN HS - Manufacturing,Manufacturing & Engineering,2710 E 89TH ST,Chicago,Illinois,60617,...,https://www.bowenhs.org,9,None,Selection Type: Lottery GPA: None HS Admis...,None,NaN,41.734627,-87.557550,POINT (-87.55755 41.734627),manufacturing
857,609863,COLUMBUS,Christopher Columbus Elementary School,ES,COLUMBUS - Open Enrollment,General Education,1003 N LEAVITT ST,Chicago,Illinois,60622,...,http://columbus.cps.edu,K-8,none,Selection Type: Lottery GPA: none Priority...,none,NaN,41.899566,-87.681938,POINT (-87.681938 41.899566),open enrollment
858,610197,TALCOTT,Mancel Talcott Elementary School,ES,TALCOTT - Dual Language,World Language,1840 W OHIO ST,Chicago,Illinois,60622,...,https://talcottfama.org,K-8,none,Selection Type: Lottery GPA: none Priority...,none,NaN,41.892405,-87.673723,POINT (-87.673723 41.892405),dual language
859,609780,MARINE LEADERSHIP AT AMES HS,Marine Leadership Academy at Ames,HS,MARINE LEADERSHIP AT AMES HS - Service Leaders...,Military & Service Leadership,1920 N HAMLIN AVE,Chicago,Illinois,60647,...,https://marine.cps.edu,9,Information Session,Selection Type: Point GPA: None HS Admissi...,Information Session,NaN,41.916045,-87.721742,POINT (-87.721742 41.916045),service leadership academy
860,610098,NOBEL,Alfred Nobel Elementary School,ES,NOBEL - Open Enrollment,General Education,4127 W HIRSCH ST,Chicago,Illinois,60651,...,http://nobel.cps.edu/,K-8,none,Selection Type: Lottery GPA: none Priority...,none,NaN,41.906155,-87.729955,POINT (-87.729955 41.906155),open enrollment

In [152]:
# retrieve the High Schools in STEM
#stem_school = df_admit[(df_admit.Program_Group == 'STEM') & (df_admit.Primary_Category == 'ES')]
stem_school = df_admit[(df_admit.Program_Group == 'STEM')]
grp_stem = stem_school.groupby(['Program_Code', 'Primary_Category'])
grp_stem.size() # view the Category of STEM Education Offered in Chicago

Program_Code          Primary_Category
Computer Programming  HS                   1
Early College STEM    HS                   5
LVLHS  - STEM         HS                   1
Magnet                ES                  11
Magnet Cluster        ES                  14
Magnet with Boundary  ES                   2
Open Enrollment       ES                   1
STEM                  HS                   7
dtype: int64

In [ ]:
grp_stem.

In [179]:
# visualization
import seaborn as sb
grp_stem.size().unstack().fillna(0)
#sb.barplot(x='Program_Code', y='', data=grp_stem)

Primary_Category        ES   HS
Program_Code
Computer Programming   0.0  1.0
Early College STEM     0.0  5.0
LVLHS  - STEM          0.0  1.0
Magnet                11.0  0.0
Magnet Cluster        14.0  0.0
Magnet with Boundary   2.0  0.0
Open Enrollment        1.0  0.0
STEM                   0.0  7.0

In [222]:
# get the count of the schools offering same program in chicago
df_pv = df_admit.pivot_table('Program_Group', index='Program_Code', columns='Primary_Category', fill_value='-', aggfunc='count')
with pan.option_context('display.max_rows', None, 'display.max_columns', 5):
    print(df_pv)

Primary_Category                                       ES    HS   MS
Program_Code
accounting                                              -   2.0    -
accounting & entrepreneurship                           -   1.0    -
agricultural sciences                                   -   3.0    -
allied health                                           -   7.0    -
architecture                                            -   4.0    -
art in motion hs - fine & performing arts               -   1.0    -
at bronzeville stem - service leadership academy        -   1.0    -
auto body repair                                        -   1.0    -
automotive technology                                   -   3.0    -
avid                                                    -   4.0    -
band                                                    -   1.0    -
broadcast technology                                    -   6.0    -
career academy                                          -   2.0    -
carpentry                                               -   1.0    -
chicago builds                                          -   1.0    -
choir                                                   -   1.0    -
computer networking                                     -   1.0    -
computer programming                                    -   1.0    -
cosmetology                                             -   2.0    -
creative writing                                        -   1.0    -
culinary arts                                           -  12.0    -
dance                                                   -   4.0    -
deaf/hard of hearing                                    -   4.0    -
diesel technology                                       -   1.0    -
digital media                                           -  12.0    -
drama                                                   -   1.0    -
dual language                                        33.0   3.0    -
early college stem                                      -   6.0    -
entrepreneurship                                        -   2.0    -
fine & performing arts                                1.0   3.0    -
fine arts & technology                                  -   2.0    -
game programming                                        -   3.0    -
game programming & web design                           -   3.0    -
general education                                     2.0  65.0    -
general education grow community                        -   1.0    -
health sciences                                         -   1.0    -
honors                                                  -   2.0    -
international baccalaureate (ib)                        -  19.0    -
international baccalaureate (ib) - myp (diploma...      -   1.0    -
international baccalaureate (ib) - myp (honors/...      -   1.0    -
jackson a - magnet                                    1.0     -    -
journalism                                              -   2.0    -
jrotc                                                   -   3.0    -
law & public safety                                     -   1.0    -
lvlhs  - allied health                                  -   2.0    -
lvlhs  - general education                              -   2.0    -
lvlhs  - stem                                           -   2.0    -
lvlhs multicultural hs - allied health                  -   1.0    -
lvlhs multicultural hs - fine & performing arts         -   2.0    -
magnet                                               41.0   2.0    -
magnet cluster                                      147.0     -  2.0
magnet with boundary                                 13.0     -    -
manufacturing                                           -   2.0    -
marketing                                               -   1.0    -
medical & health careers                                -   2.0    -
medical and health careers                              -   1.0    -
medical assisting                                       -   1.0    -
military                                                -   1.0    -
multisensory                                            -   4.0    -
music                                                   -   2.0    -
music - instrumental                                    -   1.0    -
music - instrumental - brass & woodwinds                -   1.0    -
music - instrumental - guitar                           -   1.0    -
music - instrumental - percussion                       -   1.0    -
music - instrumental - piano                            -   1.0    -
music - instrumental - strings                          -   1.0    -
music - vocal                                           -   2.0    -
musical theatre                                         -   1.0    -
north lawndale - christiana hs - general education      -   1.0    -
north lawndale - collins hs - general education         -   1.0    -
open enrollment                                     255.0   1.0  5.0
phoenix stem military hs - service leadership a...      -   1.0    -
pre-engineering                                         -   9.0    -
pre-law                                                 -   5.0    -
scholars                                                -   2.0    -
selective enrollment                                 22.0  10.0    -
selective enrollment high school                        -   8.0    -
service leadership academy                              -   4.0    -
significantly mod curr/intensive                        -  10.0    -
significantly mod curr/moderate                         -  31.0    -
stem                                                    -   8.0    -
teaching                                                -   4.0    -
theater                                                 -   1.0    -
theatre                                                 -   2.0    -
university scholars                                     -   1.0    -
visual arts                                             -   5.0    -
visual impairment                                       -   2.0    -
web development & design                                -   2.0    -